Casa:
  in_actions:
  - print_in_home
  out_actions:
  - print_out_home
  rules:
  - confidence: 0.80000000000000004
    source: connect_ssid
    value: wlan-ap
Default:
  in_actions: []
  out_actions: []
Uni:
  in_actions:
  - print_out_home
  out_actions: []
  rules:
  - confidence: 0.90000000000000002
    source: connect_ssid
    value: bglug0
  - confidence: 0.90000000000000002
    source: connect_ssid
    value: unibgfreenet
